<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AlumniSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('alumnis')->insert([
            [
                'no_induk' => '2024000001',
                'nama_siswa' => 'Faris Abdullah',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 9,
                'tanggal_lahir' => '2007-10-14',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIQ Amuntai',
            ],
            [
                'no_induk' => '2024000002',
                'nama_siswa' => 'Hanif Al-Fatih',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 9,
                'tanggal_lahir' => '2007-04-14',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STAI Rakha Amuntai',
            ],
            [
                'no_induk' => '2024000003',
                'nama_siswa' => 'Raisa Adila',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 9,
                'tanggal_lahir' => '2006-03-14',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Wirausaha Mandiri',
            ],
            [
                'no_induk' => '2024000004',
                'nama_siswa' => 'Zaskia Nuraini',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 9,
                'tanggal_lahir' => '2007-10-06',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'PT Adaro Indonesia',
            ],
            [
                'no_induk' => '2024000005',
                'nama_siswa' => 'Gibran Rakabuming',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 9,
                'tanggal_lahir' => '2006-01-28',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UIN Antasari Banjarmasin',
            ],
            [
                'no_induk' => '2024000006',
                'nama_siswa' => 'Aulia Rahman',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 9,
                'tanggal_lahir' => '2006-05-18',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIA Amuntai',
            ],
            [
                'no_induk' => '2024000007',
                'nama_siswa' => 'Nadia Safitri',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 9,
                'tanggal_lahir' => '2006-06-03',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Wirausaha Mandiri',
            ],
            [
                'no_induk' => '2024000008',
                'nama_siswa' => 'Kamila Zahrani',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 9,
                'tanggal_lahir' => '2007-12-13',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Toko Keluarga Barokah',
            ],
            [
                'no_induk' => '2024000009',
                'nama_siswa' => 'Rafi Ahmad Sanusi',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 9,
                'tanggal_lahir' => '2007-01-17',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STAI Rakha Amuntai',
            ],
            [
                'no_induk' => '2024000010',
                'nama_siswa' => 'Syauqi Maulana',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 9,
                'tanggal_lahir' => '2007-11-14',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'PT Adaro Indonesia',
            ],
            [
                'no_induk' => '2024000011',
                'nama_siswa' => 'Luthfi Hasan',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 9,
                'tanggal_lahir' => '2007-09-26',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIQ Amuntai',
            ],
            [
                'no_induk' => '2024000012',
                'nama_siswa' => 'Salwa Kamila',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 9,
                'tanggal_lahir' => '2006-06-12',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UNISKA Muhammad Arsyad Al Banjari',
            ],
            [
                'no_induk' => '2024000013',
                'nama_siswa' => 'Tariq Halilintar',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 9,
                'tanggal_lahir' => '2006-01-12',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIQ Amuntai',
            ],
            [
                'no_induk' => '2024000014',
                'nama_siswa' => 'Fadlan Muhammad',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 9,
                'tanggal_lahir' => '2006-08-27',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Poltekkes Banjarmasin',
            ],
            [
                'no_induk' => '2024000015',
                'nama_siswa' => 'Zainuddin Al-Banjari',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 9,
                'tanggal_lahir' => '2006-05-15',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STAI Rakha Amuntai',
            ],
            [
                'no_induk' => '2024000016',
                'nama_siswa' => 'Annisa Fitriani',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 9,
                'tanggal_lahir' => '2007-02-15',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UNISKA Muhammad Arsyad Al Banjari',
            ],
            [
                'no_induk' => '2024000017',
                'nama_siswa' => 'Putri Handayani',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 9,
                'tanggal_lahir' => '2006-04-07',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Bank Kalsel Syariah',
            ],
            [
                'no_induk' => '2024000018',
                'nama_siswa' => 'Rahmat Hidayatullah',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 9,
                'tanggal_lahir' => '2007-11-18',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UNISKA Muhammad Arsyad Al Banjari',
            ],
            [
                'no_induk' => '2024000019',
                'nama_siswa' => 'Jamaluddin Suriansyah',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 9,
                'tanggal_lahir' => '2007-12-16',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STAI Rakha Amuntai',
            ],
            [
                'no_induk' => '2024000020',
                'nama_siswa' => 'Husna Amalia',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 9,
                'tanggal_lahir' => '2006-06-09',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIQ Amuntai',
            ],
        ]);
    }
}
