<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AlumniSeederPart2 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('alumnis')->insert([
            [
                'no_induk' => '2024000021',
                'nama_siswa' => 'Arfan Maulana',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 10,
                'tanggal_lahir' => '2007-04-16',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UNISKA Muhammad Arsyad Al Banjari',
            ],
            [
                'no_induk' => '2024000022',
                'nama_siswa' => 'Bilqis Humaira',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 10,
                'tanggal_lahir' => '2007-05-05',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STAI Rakha Amuntai',
            ],
            [
                'no_induk' => '2024000023',
                'nama_siswa' => 'Daffa Ardiansyah',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 10,
                'tanggal_lahir' => '2007-04-29',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UIN Antasari Banjarmasin',
            ],
            [
                'no_induk' => '2024000024',
                'nama_siswa' => 'Erlina Sari',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-09-23',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Bank Kalsel Syariah',
            ],
            [
                'no_induk' => '2024000025',
                'nama_siswa' => 'Fikri Haikal',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-07-27',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Poltekkes Banjarmasin',
            ],
            [
                'no_induk' => '2024000026',
                'nama_siswa' => 'Ghina Salsabila',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 10,
                'tanggal_lahir' => '2007-08-15',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'PT Adaro Indonesia',
            ],
            [
                'no_induk' => '2024000027',
                'nama_siswa' => 'Hafiz Al-Asad',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-06-08',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Bank Kalsel Syariah',
            ],
            [
                'no_induk' => '2024000028',
                'nama_siswa' => 'Indah Cahyani',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 10,
                'tanggal_lahir' => '2007-01-07',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Wirausaha Mandiri',
            ],
            [
                'no_induk' => '2024000029',
                'nama_siswa' => 'Jihan Almira',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 10,
                'tanggal_lahir' => '2007-01-11',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UNISKA Muhammad Arsyad Al Banjari',
            ],
            [
                'no_induk' => '2024000030',
                'nama_siswa' => 'Khalid Walid',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 10,
                'tanggal_lahir' => '2007-01-13',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UNISKA Muhammad Arsyad Al Banjari',
            ],
            [
                'no_induk' => '2024000031',
                'nama_siswa' => 'Lestari Indah',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-12-06',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Poltekkes Banjarmasin',
            ],
            [
                'no_induk' => '2024000032',
                'nama_siswa' => 'Maulana Yusuf',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-09-23',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIQ Amuntai',
            ],
            [
                'no_induk' => '2024000033',
                'nama_siswa' => 'Nabila Putri',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-03-05',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UIN Antasari Banjarmasin',
            ],
            [
                'no_induk' => '2024000034',
                'nama_siswa' => 'Omar Abdullah',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-04-22',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Poltekkes Banjarmasin',
            ],
            [
                'no_induk' => '2024000035',
                'nama_siswa' => 'Qonita Aulia',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-01-12',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIA Amuntai',
            ],
            [
                'no_induk' => '2024000036',
                'nama_siswa' => 'Rasyid Ridho',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 10,
                'tanggal_lahir' => '2007-11-21',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UIN Antasari Banjarmasin',
            ],
            [
                'no_induk' => '2024000037',
                'nama_siswa' => 'Salsabila Az-Zahra',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-03-04',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIQ Amuntai',
            ],
            [
                'no_induk' => '2024000038',
                'nama_siswa' => 'Taufiqurrahman',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-09-01',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UIN Antasari Banjarmasin',
            ],
            [
                'no_induk' => '2024000039',
                'nama_siswa' => 'Umar Al-FarUQ',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 10,
                'tanggal_lahir' => '2007-12-02',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Dinas Pendidikan Kab. HSU',
            ],
            [
                'no_induk' => '2024000040',
                'nama_siswa' => 'Vina Alvionita',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 10,
                'tanggal_lahir' => '2006-11-05',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UIN Antasari Banjarmasin',
            ],
        ]);
    }
}
