<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AlumniSeederPart4 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('alumnis')->insert([
            [
                'no_induk' => '2024000061',
                'nama_siswa' => 'Wahyu Pratama',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 12,
                'tanggal_lahir' => '2006-06-17',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIA Amuntai',
            ],
            [
                'no_induk' => '2024000062',
                'nama_siswa' => 'Xena Maulina',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 12,
                'tanggal_lahir' => '2006-11-20',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UIN Antasari Banjarmasin',
            ],
            [
                'no_induk' => '2024000063',
                'nama_siswa' => 'Yasmine Putri',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 12,
                'tanggal_lahir' => '2006-06-15',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIQ Amuntai',
            ],
            [
                'no_induk' => '2024000064',
                'nama_siswa' => 'Zidan Al-Ghifari',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 12,
                'tanggal_lahir' => '2006-06-12',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000065',
                'nama_siswa' => 'Alya Nurhasanah',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 12,
                'tanggal_lahir' => '2007-10-18',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UNISKA Muhammad Arsyad Al Banjari',
            ],
            [
                'no_induk' => '2024000066',
                'nama_siswa' => 'Bima Sakti',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 12,
                'tanggal_lahir' => '2006-08-28',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Pondok Pesantren Modern',
            ],
            [
                'no_induk' => '2024000067',
                'nama_siswa' => 'Cantika Dewi',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 12,
                'tanggal_lahir' => '2007-08-18',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIA Amuntai',
            ],
            [
                'no_induk' => '2024000068',
                'nama_siswa' => 'Doni Setiawan',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 12,
                'tanggal_lahir' => '2007-10-08',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIQ Amuntai',
            ],
            [
                'no_induk' => '2024000069',
                'nama_siswa' => 'Eliza Fitri',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 12,
                'tanggal_lahir' => '2006-12-04',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UIN Antasari Banjarmasin',
            ],
            [
                'no_induk' => '2024000070',
                'nama_siswa' => 'Fahri Hamzah',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 12,
                'tanggal_lahir' => '2006-03-14',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STAI Rakha Amuntai',
            ],
            [
                'no_induk' => '2024000071',
                'nama_siswa' => 'Gita Gutawa',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 12,
                'tanggal_lahir' => '2007-10-02',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000072',
                'nama_siswa' => 'Hendri Gunawan',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 12,
                'tanggal_lahir' => '2006-08-15',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000073',
                'nama_siswa' => 'Intan Permata',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 12,
                'tanggal_lahir' => '2006-01-03',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000074',
                'nama_siswa' => 'Jefri Nichol',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 12,
                'tanggal_lahir' => '2006-07-04',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STAI Rakha Amuntai',
            ],
            [
                'no_induk' => '2024000075',
                'nama_siswa' => 'Kevin Sanjaya',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 12,
                'tanggal_lahir' => '2007-03-30',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIA Amuntai',
            ],
            [
                'no_induk' => '2024000076',
                'nama_siswa' => 'Lia Amelia',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 12,
                'tanggal_lahir' => '2007-06-26',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UIN Antasari Banjarmasin',
            ],
            [
                'no_induk' => '2024000077',
                'nama_siswa' => 'Mawar de Jongh',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 12,
                'tanggal_lahir' => '2007-03-07',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Poltekkes Banjarmasin',
            ],
            [
                'no_induk' => '2024000078',
                'nama_siswa' => 'Nino Fernandez',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 12,
                'tanggal_lahir' => '2007-05-15',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Poltekkes Banjarmasin',
            ],
            [
                'no_induk' => '2024000079',
                'nama_siswa' => 'Oscar Lawalata',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 12,
                'tanggal_lahir' => '2007-02-22',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000080',
                'nama_siswa' => 'Putri Marino',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 12,
                'tanggal_lahir' => '2007-02-04',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'PT Adaro Indonesia',
            ],
        ]);
    }
}
