<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AlumniSeederPart3 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('alumnis')->insert([
            [
                'no_induk' => '2024000041',
                'nama_siswa' => 'Adinda Kirana',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 11,
                'tanggal_lahir' => '2007-01-15',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000042',
                'nama_siswa' => 'Bagas Pramudya',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-06-12',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIQ Amuntai',
            ],
            [
                'no_induk' => '2024000043',
                'nama_siswa' => 'Citra Lestari',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 11,
                'tanggal_lahir' => '2007-11-13',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000044',
                'nama_siswa' => 'Dian Anggraini',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-02-11',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'PT Adaro Indonesia',
            ],
            [
                'no_induk' => '2024000045',
                'nama_siswa' => 'Eka Saputra',
                'tempat_lahir' => 'Amuntai',
                'rooms_id' => 11,
                'tanggal_lahir' => '2007-09-26',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIA Amuntai',
            ],
            [
                'no_induk' => '2024000046',
                'nama_siswa' => 'Fitria Handayani',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-11-20',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UNISKA Muhammad Arsyad Al Banjari',
            ],
            [
                'no_induk' => '2024000047',
                'nama_siswa' => 'Galih Wijaya',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 11,
                'tanggal_lahir' => '2007-02-27',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000048',
                'nama_siswa' => 'Hana Malihah',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-11-18',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000049',
                'nama_siswa' => 'Irfan Hakim',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-06-12',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIQ Amuntai',
            ],
            [
                'no_induk' => '2024000050',
                'nama_siswa' => 'Joko Susilo',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-12-21',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Dinas Pendidikan Kab. HSU',
            ],
            [
                'no_induk' => '2024000051',
                'nama_siswa' => 'Kartika Chandra',
                'tempat_lahir' => 'Banjarmasin',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-02-26',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000052',
                'nama_siswa' => 'Lutfi Aulia',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 11,
                'tanggal_lahir' => '2007-06-14',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'PT Adaro Indonesia',
            ],
            [
                'no_induk' => '2024000053',
                'nama_siswa' => 'Mega Wati',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 11,
                'tanggal_lahir' => '2007-09-14',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIA Amuntai',
            ],
            [
                'no_induk' => '2024000054',
                'nama_siswa' => 'Nanda Pratama',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 11,
                'tanggal_lahir' => '2007-07-04',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Wirausaha Mandiri',
            ],
            [
                'no_induk' => '2024000055',
                'nama_siswa' => 'Olivia Zahra',
                'tempat_lahir' => 'Barabai',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-01-06',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Poltekkes Banjarmasin',
            ],
            [
                'no_induk' => '2024000056',
                'nama_siswa' => 'Putra Perkasa',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-07-16',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'Universitas Lambung Mangkurat',
            ],
            [
                'no_induk' => '2024000057',
                'nama_siswa' => 'Qanita Syakira',
                'tempat_lahir' => 'Tanjung',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-09-09',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Bekerja',
                'nama_tempat' => 'Bank Kalsel Syariah',
            ],
            [
                'no_induk' => '2024000058',
                'nama_siswa' => 'Rendi Andika',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 11,
                'tanggal_lahir' => '2007-06-07',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'UIN Antasari Banjarmasin',
            ],
            [
                'no_induk' => '2024000059',
                'nama_siswa' => 'Siska Amelia',
                'tempat_lahir' => 'Pelaihari',
                'rooms_id' => 11,
                'tanggal_lahir' => '2006-06-21',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STAI Rakha Amuntai',
            ],
            [
                'no_induk' => '2024000060',
                'nama_siswa' => 'Tegar Satria',
                'tempat_lahir' => 'Martapura',
                'rooms_id' => 11,
                'tanggal_lahir' => '2007-03-12',
                'academic_periods_id' => 2,
                'melanjutkan' => 'Kuliah',
                'nama_tempat' => 'STIA Amuntai',
            ],
        ]);
    }
}
