<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KesehatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('health_cares')->insert([
            [
                'nama_siswa' => 'Yasmin Salsabila',
                'student_id' => 140,
                'kelas' => 'X D',
                'keluhan' => 'Sakit gigi',
                'orang_tua' => 'Indah',
                'alamat' => 'Cempaka',
                'hasil_pemeriksaan' => 'Diberi obat pereda nyeri dan disarankan untuk segera periksa ke dokter gigi sepulang sekolah.',
                'tanggal' => '2025-07-31',
                'created_at' => '2025-07-31 00:00:00',
                'updated_at' => '2025-07-31 00:00:00',
            ],
            [
                'nama_siswa' => 'Lia Agustina',
                'student_id' => 61,
                'kelas' => 'X B',
                'keluhan' => 'Luka lecet di lutut akibat terjatuh',
                'orang_tua' => 'Ali',
                'alamat' => 'Telaga Silaba',
                'hasil_pemeriksaan' => 'Luka dibersihkan dengan cairan antiseptik, diberi obat merah dan ditutup dengan plester.',
                'tanggal' => '2025-07-22',
                'created_at' => '2025-07-22 00:00:00',
                'updated_at' => '2025-07-22 00:00:00',
            ],
            [
                'nama_siswa' => 'Abdul Rahman Hakim',
                'student_id' => 35,
                'kelas' => 'X A',
                'keluhan' => 'Sakit gigi',
                'orang_tua' => 'Muhammad',
                'alamat' => 'Cangkering',
                'hasil_pemeriksaan' => 'Diberi obat pereda nyeri dan disarankan untuk segera periksa ke dokter gigi sepulang sekolah.',
                'tanggal' => '2025-07-29',
                'created_at' => '2025-07-29 00:00:00',
                'updated_at' => '2025-07-29 00:00:00',
            ],
            [
                'nama_siswa' => 'Aulia Putri Salsabila',
                'student_id' => 69,
                'kelas' => 'X C',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Siti',
                'alamat' => 'Pulau Tambak',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-07-18',
                'created_at' => '2025-07-18 00:00:00',
                'updated_at' => '2025-07-18 00:00:00',
            ],
            [
                'nama_siswa' => 'Agung Setiawan',
                'student_id' => 78,
                'kelas' => 'X C',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Rina',
                'alamat' => 'Kutai Kecil',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-07-15',
                'created_at' => '2025-07-15 00:00:00',
                'updated_at' => '2025-07-15 00:00:00',
            ],
            [
                'nama_siswa' => 'Lia Agustina',
                'student_id' => 61,
                'kelas' => 'X B',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Putri',
                'alamat' => 'Jumba',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-07-31',
                'created_at' => '2025-07-31 00:00:00',
                'updated_at' => '2025-07-31 00:00:00',
            ],
            [
                'nama_siswa' => 'Annisa Rahmawati',
                'student_id' => 47,
                'kelas' => 'X B',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Yusuf',
                'alamat' => 'Murung Panggang',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-07-18',
                'created_at' => '2025-07-18 00:00:00',
                'updated_at' => '2025-07-18 00:00:00',
            ],
            [
                'nama_siswa' => 'Hasanah Fitriani',
                'student_id' => 142,
                'kelas' => 'X D',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Reza',
                'alamat' => 'Telaga Silaba',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-07-18',
                'created_at' => '2025-07-18 00:00:00',
                'updated_at' => '2025-07-18 00:00:00',
            ],
            [
                'nama_siswa' => 'Maya Sari',
                'student_id' => 55,
                'kelas' => 'X B',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Hasan',
                'alamat' => 'Pulau Tambak',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-07-14',
                'created_at' => '2025-07-14 00:00:00',
                'updated_at' => '2025-07-14 00:00:00',
            ],
            [
                'nama_siswa' => 'Khadijah Al-Kubro',
                'student_id' => 134,
                'kelas' => 'X D',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Ali',
                'alamat' => 'Ujung Murung',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-07-14',
                'created_at' => '2025-07-14 00:00:00',
                'updated_at' => '2025-07-14 00:00:00',
            ],
            [
                'nama_siswa' => 'Nadia Aulia',
                'student_id' => 53,
                'kelas' => 'X B',
                'keluhan' => 'Sakit gigi',
                'orang_tua' => 'Agus',
                'alamat' => 'Kayakah',
                'hasil_pemeriksaan' => 'Diberi obat pereda nyeri dan disarankan untuk segera periksa ke dokter gigi sepulang sekolah.',
                'tanggal' => '2025-07-24',
                'created_at' => '2025-07-24 00:00:00',
                'updated_at' => '2025-07-24 00:00:00',
            ],
            [
                'nama_siswa' => 'Agung Setiawan',
                'student_id' => 78,
                'kelas' => 'X C',
                'keluhan' => 'Sakit perut dan mual',
                'orang_tua' => 'Ani',
                'alamat' => 'Cangkering',
                'hasil_pemeriksaan' => 'Diberi minyak kayu putih dan teh hangat, diizinkan istirahat di UKS.',
                'tanggal' => '2025-07-23',
                'created_at' => '2025-07-23 00:00:00',
                'updated_at' => '2025-07-23 00:00:00',
            ],
            [
                'nama_siswa' => 'Dimas Saputra',
                'student_id' => 62,
                'kelas' => 'X B',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Budi',
                'alamat' => 'Cangkering',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-07-30',
                'created_at' => '2025-07-30 00:00:00',
                'updated_at' => '2025-07-30 00:00:00',
            ],
            [
                'nama_siswa' => 'Reza',
                'student_id' => 141,
                'kelas' => 'X D',
                'keluhan' => 'Luka lecet di lutut akibat terjatuh',
                'orang_tua' => 'Nur',
                'alamat' => 'Simpang Tiga',
                'hasil_pemeriksaan' => 'Luka dibersihkan dengan cairan antiseptik, diberi obat merah dan ditutup dengan plester.',
                'tanggal' => '2025-07-18',
                'created_at' => '2025-07-18 00:00:00',
                'updated_at' => '2025-07-18 00:00:00',
            ],
            [
                'nama_siswa' => 'Dewi Lestari',
                'student_id' => 49,
                'kelas' => 'X B',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Abdul',
                'alamat' => 'Mamar',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-07-24',
                'created_at' => '2025-07-24 00:00:00',
                'updated_at' => '2025-07-24 00:00:00',
            ],
            [
                'nama_siswa' => 'Zainab Aliyah',
                'student_id' => 138,
                'kelas' => 'X D',
                'keluhan' => 'Sakit perut dan mual',
                'orang_tua' => 'Rina',
                'alamat' => 'Jarang Kuantan',
                'hasil_pemeriksaan' => 'Diberi minyak kayu putih dan teh hangat, diizinkan istirahat di UKS.',
                'tanggal' => '2025-07-30',
                'created_at' => '2025-07-30 00:00:00',
                'updated_at' => '2025-07-30 00:00:00',
            ],
            [
                'nama_siswa' => 'Aulia Putri Salsabila',
                'student_id' => 69,
                'kelas' => 'X C',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Yusuf',
                'alamat' => 'Mamar',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-07-31',
                'created_at' => '2025-07-31 00:00:00',
                'updated_at' => '2025-07-31 00:00:00',
            ],
            [
                'nama_siswa' => 'Citra Kirana',
                'student_id' => 64,
                'kelas' => 'X B',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Joko',
                'alamat' => 'Telaga Silaba',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-07-17',
                'created_at' => '2025-07-17 00:00:00',
                'updated_at' => '2025-07-17 00:00:00',
            ],
            [
                'nama_siswa' => 'Rizki Maulana Ibrahim',
                'student_id' => 28,
                'kelas' => 'X A',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Yusuf',
                'alamat' => 'Jarang Kuantan',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-08-01',
                'created_at' => '2025-08-01 00:00:00',
                'updated_at' => '2025-08-01 00:00:00',
            ],
            [
                'nama_siswa' => 'Annisa Rahmawati',
                'student_id' => 47,
                'kelas' => 'X B',
                'keluhan' => 'Sakit perut dan mual',
                'orang_tua' => 'Lina',
                'alamat' => 'Murung Panggang',
                'hasil_pemeriksaan' => 'Diberi minyak kayu putih dan teh hangat, diizinkan istirahat di UKS.',
                'tanggal' => '2025-07-28',
                'created_at' => '2025-07-28 00:00:00',
                'updated_at' => '2025-07-28 00:00:00',
            ],
            [
                'nama_siswa' => 'Handoko Aji',
                'student_id' => 76,
                'kelas' => 'X C',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Reza',
                'alamat' => 'Kota Raja',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-07-29',
                'created_at' => '2025-07-29 00:00:00',
                'updated_at' => '2025-07-29 00:00:00',
            ],
            [
                'nama_siswa' => 'Wildan Al-Farisi',
                'student_id' => 65,
                'kelas' => 'X B',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Yusuf',
                'alamat' => 'Rukama',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-07-22',
                'created_at' => '2025-07-22 00:00:00',
                'updated_at' => '2025-07-22 00:00:00',
            ],
            [
                'nama_siswa' => 'Linda Wati',
                'student_id' => 81,
                'kelas' => 'X C',
                'keluhan' => 'Sakit gigi',
                'orang_tua' => 'Ali',
                'alamat' => 'Harusan Telaga',
                'hasil_pemeriksaan' => 'Diberi obat pereda nyeri dan disarankan untuk segera periksa ke dokter gigi sepulang sekolah.',
                'tanggal' => '2025-07-31',
                'created_at' => '2025-07-31 00:00:00',
                'updated_at' => '2025-07-31 00:00:00',
            ],
            [
                'nama_siswa' => 'Lia Agustina',
                'student_id' => 61,
                'kelas' => 'X B',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Ali',
                'alamat' => 'Kutai Kecil',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-07-21',
                'created_at' => '2025-07-21 00:00:00',
                'updated_at' => '2025-07-21 00:00:00',
            ],
            [
                'nama_siswa' => 'Maya Sari',
                'student_id' => 55,
                'kelas' => 'X B',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Putri',
                'alamat' => 'Keramat',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-07-30',
                'created_at' => '2025-07-30 00:00:00',
                'updated_at' => '2025-07-30 00:00:00',
            ],
        ]);
    }
}
