<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KesehatanAgustusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('health_cares')->insert([
            [
                'nama_siswa' => 'Siti Aisyah Putri',
                'student_id' => 29,
                'kelas' => 'X A',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Reza',
                'alamat' => 'Kayakah',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-08-08',
                'created_at' => '2025-08-08 00:00:00',
                'updated_at' => '2025-08-08 00:00:00',
            ],
            [
                'nama_siswa' => 'Iqbal',
                'student_id' => 135,
                'kelas' => 'X D',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Joko',
                'alamat' => 'Kayakah',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-08-28',
                'created_at' => '2025-08-28 00:00:00',
                'updated_at' => '2025-08-28 00:00:00',
            ],
            [
                'nama_siswa' => 'Ahmad Fauzan Al-Ghifari',
                'student_id' => 27,
                'kelas' => 'X A',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Indah',
                'alamat' => 'Cangkering',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-08-14',
                'created_at' => '2025-08-14 00:00:00',
                'updated_at' => '2025-08-14 00:00:00',
            ],
            [
                'nama_siswa' => 'Fatimah Az-Zahra',
                'student_id' => 31,
                'kelas' => 'X A',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Agus',
                'alamat' => 'Mamar',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-08-22',
                'created_at' => '2025-08-22 00:00:00',
                'updated_at' => '2025-08-22 00:00:00',
            ],
            [
                'nama_siswa' => 'Jamaludin',
                'student_id' => 82,
                'kelas' => 'X C',
                'keluhan' => 'Merasa lemas dan tidak enak badan',
                'orang_tua' => 'Muhammad',
                'alamat' => 'Cempaka',
                'hasil_pemeriksaan' => 'Diizinkan pulang setelah orang tua menjemput.',
                'tanggal' => '2025-08-19',
                'created_at' => '2025-08-19 00:00:00',
                'updated_at' => '2025-08-19 00:00:00',
            ],
            [
                'nama_siswa' => 'Rizky Akbar Pratama',
                'student_id' => 46,
                'kelas' => 'X B',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Ali',
                'alamat' => 'Banyu Hirang',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-08-18',
                'created_at' => '2025-08-18 00:00:00',
                'updated_at' => '2025-08-18 00:00:00',
            ],
            [
                'nama_siswa' => 'Yusuf Ali Alatas',
                'student_id' => 33,
                'kelas' => 'X A',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Joko',
                'alamat' => 'Kota Raja',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-08-25',
                'created_at' => '2025-08-25 00:00:00',
                'updated_at' => '2025-08-25 00:00:00',
            ],
            [
                'nama_siswa' => 'Yusuf Ibrahim',
                'student_id' => 133,
                'kelas' => 'X D',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Siti',
                'alamat' => 'Murung Panggang',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-08-27',
                'created_at' => '2025-08-27 00:00:00',
                'updated_at' => '2025-08-27 00:00:00',
            ],
            [
                'nama_siswa' => 'Bunga Citra Lestari',
                'student_id' => 67,
                'kelas' => 'X C',
                'keluhan' => 'Merasa lemas dan tidak enak badan',
                'orang_tua' => 'Ahmad',
                'alamat' => 'Rukama',
                'hasil_pemeriksaan' => 'Diizinkan pulang setelah orang tua menjemput.',
                'tanggal' => '2025-08-18',
                'created_at' => '2025-08-18 00:00:00',
                'updated_at' => '2025-08-18 00:00:00',
            ],
            [
                'nama_siswa' => 'Abdul Rahman Hakim',
                'student_id' => 35,
                'kelas' => 'X A',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Hasan',
                'alamat' => 'Ilir Pemangkih',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-08-29',
                'created_at' => '2025-08-29 00:00:00',
                'updated_at' => '2025-08-29 00:00:00',
            ],
            [
                'nama_siswa' => 'Maya Sari',
                'student_id' => 55,
                'kelas' => 'X B',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Ahmad',
                'alamat' => 'Mamar',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-08-18',
                'created_at' => '2025-08-18 00:00:00',
                'updated_at' => '2025-08-18 00:00:00',
            ],
            [
                'nama_siswa' => 'Aditya Nugraha',
                'student_id' => 40,
                'kelas' => 'X A',
                'keluhan' => 'Merasa lemas dan tidak enak badan',
                'orang_tua' => 'Rina',
                'alamat' => 'Teluk Paring',
                'hasil_pemeriksaan' => 'Diizinkan pulang setelah orang tua menjemput.',
                'tanggal' => '2025-08-13',
                'created_at' => '2025-08-13 00:00:00',
                'updated_at' => '2025-08-13 00:00:00',
            ],
            [
                'nama_siswa' => 'Siti Aisyah Putri',
                'student_id' => 29,
                'kelas' => 'X A',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Muhammad',
                'alamat' => 'Rukama',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-08-21',
                'created_at' => '2025-08-21 00:00:00',
                'updated_at' => '2025-08-21 00:00:00',
            ],
            [
                'nama_siswa' => 'Handoko Aji',
                'student_id' => 76,
                'kelas' => 'X C',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Budi',
                'alamat' => 'Cempaka',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-08-25',
                'created_at' => '2025-08-25 00:00:00',
                'updated_at' => '2025-08-25 00:00:00',
            ],
            [
                'nama_siswa' => 'Zainal Arifin',
                'student_id' => 34,
                'kelas' => 'X A',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Dewi',
                'alamat' => 'Keramat',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-08-26',
                'created_at' => '2025-08-26 00:00:00',
                'updated_at' => '2025-08-26 00:00:00',
            ],
            [
                'nama_siswa' => 'Khadijah Al-Kubro',
                'student_id' => 134,
                'kelas' => 'X D',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Reza',
                'alamat' => 'Keramat',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-08-19',
                'created_at' => '2025-08-19 00:00:00',
                'updated_at' => '2025-08-19 00:00:00',
            ],
            [
                'nama_siswa' => 'Fajar Maulana Siddiq',
                'student_id' => 48,
                'kelas' => 'X B',
                'keluhan' => 'Sakit gigi',
                'orang_tua' => 'Rina',
                'alamat' => 'Harusan Telaga',
                'hasil_pemeriksaan' => 'Diberi obat pereda nyeri dan disarankan untuk segera periksa ke dokter gigi sepulang sekolah.',
                'tanggal' => '2025-08-04',
                'created_at' => '2025-08-04 00:00:00',
                'updated_at' => '2025-08-04 00:00:00',
            ],
            [
                'nama_siswa' => 'Yusuf Ali Alatas',
                'student_id' => 33,
                'kelas' => 'X A',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Ahmad',
                'alamat' => 'Keramat',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-08-05',
                'created_at' => '2025-08-05 00:00:00',
                'updated_at' => '2025-08-05 00:00:00',
            ],
            [
                'nama_siswa' => 'Nadia Aulia',
                'student_id' => 53,
                'kelas' => 'X B',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Nur',
                'alamat' => 'Kota Raja',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-08-25',
                'created_at' => '2025-08-25 00:00:00',
                'updated_at' => '2025-08-25 00:00:00',
            ],
            [
                'nama_siswa' => 'Muhammad Alif Pratama',
                'student_id' => 123,
                'kelas' => 'X D',
                'keluhan' => 'Sakit perut dan mual',
                'orang_tua' => 'Siti',
                'alamat' => 'Cangkering',
                'hasil_pemeriksaan' => 'Diberi minyak kayu putih dan teh hangat, diizinkan istirahat di UKS.',
                'tanggal' => '2025-08-14',
                'created_at' => '2025-08-14 00:00:00',
                'updated_at' => '2025-08-14 00:00:00',
            ],
            [
                'nama_siswa' => 'Maya Sari',
                'student_id' => 55,
                'kelas' => 'X B',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Ali',
                'alamat' => 'Murung Panggang',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-08-26',
                'created_at' => '2025-08-26 00:00:00',
                'updated_at' => '2025-08-26 00:00:00',
            ],
            [
                'nama_siswa' => 'Sari Mutiara',
                'student_id' => 71,
                'kelas' => 'X C',
                'keluhan' => 'Mimisan',
                'orang_tua' => 'Dewi',
                'alamat' => 'Ilir Pemangkih',
                'hasil_pemeriksaan' => 'Diberi pertolongan pertama dengan menjepit hidung dan diminta untuk menunduk. Diistirahatkan di UKS hingga berhenti.',
                'tanggal' => '2025-08-28',
                'created_at' => '2025-08-28 00:00:00',
                'updated_at' => '2025-08-28 00:00:00',
            ],
            [
                'nama_siswa' => 'Dian Novita Sari',
                'student_id' => 73,
                'kelas' => 'X C',
                'keluhan' => 'Sakit perut dan mual',
                'orang_tua' => 'Hasan',
                'alamat' => 'Murung Panggang',
                'hasil_pemeriksaan' => 'Diberi minyak kayu putih dan teh hangat, diizinkan istirahat di UKS.',
                'tanggal' => '2025-08-11',
                'created_at' => '2025-08-11 00:00:00',
                'updated_at' => '2025-08-11 00:00:00',
            ],
            [
                'nama_siswa' => 'Muhammad Alif Pratama',
                'student_id' => 123,
                'kelas' => 'X D',
                'keluhan' => 'Luka lecet di lutut akibat terjatuh',
                'orang_tua' => 'Budi',
                'alamat' => 'Kayakah',
                'hasil_pemeriksaan' => 'Luka dibersihkan dengan cairan antiseptik, diberi obat merah dan ditutup dengan plester.',
                'tanggal' => '2025-08-06',
                'created_at' => '2025-08-06 00:00:00',
                'updated_at' => '2025-08-06 00:00:00',
            ],
            [
                'nama_siswa' => 'Maya Sari',
                'student_id' => 55,
                'kelas' => 'X B',
                'keluhan' => 'Luka lecet di lutut akibat terjatuh',
                'orang_tua' => 'Hasan',
                'alamat' => 'Rukama',
                'hasil_pemeriksaan' => 'Luka dibersihkan dengan cairan antiseptik, diberi obat merah dan ditutup dengan plester.',
                'tanggal' => '2025-08-20',
                'created_at' => '2025-08-20 00:00:00',
                'updated_at' => '2025-08-20 00:00:00',
            ],
            [
                'nama_siswa' => 'Ahmad Fauzan Al-Ghifari',
                'student_id' => 27,
                'kelas' => 'X A',
                'keluhan' => 'Merasa lemas dan tidak enak badan',
                'orang_tua' => 'Ani',
                'alamat' => 'Murung Panggang',
                'hasil_pemeriksaan' => 'Diizinkan pulang setelah orang tua menjemput.',
                'tanggal' => '2025-08-18',
                'created_at' => '2025-08-18 00:00:00',
                'updated_at' => '2025-08-18 00:00:00',
            ],
            [
                'nama_siswa' => 'Fahmi Aziz',
                'student_id' => 66,
                'kelas' => 'X C',
                'keluhan' => 'Sakit gigi',
                'orang_tua' => 'Ani',
                'alamat' => 'Teluk Paring',
                'hasil_pemeriksaan' => 'Diberi obat pereda nyeri dan disarankan untuk segera periksa ke dokter gigi sepulang sekolah.',
                'tanggal' => '2025-08-11',
                'created_at' => '2025-08-11 00:00:00',
                'updated_at' => '2025-08-11 00:00:00',
            ],
            [
                'nama_siswa' => 'Yusuf Ali Alatas',
                'student_id' => 33,
                'kelas' => 'X A',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Nur',
                'alamat' => 'Rukama',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-08-15',
                'created_at' => '2025-08-15 00:00:00',
                'updated_at' => '2025-08-15 00:00:00',
            ],
            [
                'nama_siswa' => 'Bunga Citra Lestari',
                'student_id' => 67,
                'kelas' => 'X C',
                'keluhan' => 'Merasa lemas dan tidak enak badan',
                'orang_tua' => 'Sri',
                'alamat' => 'Harusan Telaga',
                'hasil_pemeriksaan' => 'Diizinkan pulang setelah orang tua menjemput.',
                'tanggal' => '2025-08-08',
                'created_at' => '2025-08-08 00:00:00',
                'updated_at' => '2025-08-08 00:00:00',
            ],
            [
                'nama_siswa' => 'Dimas Setiawan',
                'student_id' => 137,
                'kelas' => 'X D',
                'keluhan' => 'Merasa lemas dan tidak enak badan',
                'orang_tua' => 'Nur',
                'alamat' => 'Harusan Telaga',
                'hasil_pemeriksaan' => 'Diizinkan pulang setelah orang tua menjemput.',
                'tanggal' => '2025-08-20',
                'created_at' => '2025-08-20 00:00:00',
                'updated_at' => '2025-08-20 00:00:00',
            ],
            [
                'nama_siswa' => 'Rangga Dwi Saputra',
                'student_id' => 68,
                'kelas' => 'X C',
                'keluhan' => 'Luka lecet di lutut akibat terjatuh',
                'orang_tua' => 'Lina',
                'alamat' => 'Telaga Silaba',
                'hasil_pemeriksaan' => 'Luka dibersihkan dengan cairan antiseptik, diberi obat merah dan ditutup dengan plester.',
                'tanggal' => '2025-08-12',
                'created_at' => '2025-08-12 00:00:00',
                'updated_at' => '2025-08-12 00:00:00',
            ],
            [
                'nama_siswa' => 'Rizki Maulana',
                'student_id' => 131,
                'kelas' => 'X D',
                'keluhan' => 'Sakit gigi',
                'orang_tua' => 'Sri',
                'alamat' => 'Keramat',
                'hasil_pemeriksaan' => 'Diberi obat pereda nyeri dan disarankan untuk segera periksa ke dokter gigi sepulang sekolah.',
                'tanggal' => '2025-08-21',
                'created_at' => '2025-08-21 00:00:00',
                'updated_at' => '2025-08-21 00:00:00',
            ],
            [
                'nama_siswa' => 'Taufik Hidayat',
                'student_id' => 80,
                'kelas' => 'X C',
                'keluhan' => 'Demam ringan',
                'orang_tua' => 'Siti',
                'alamat' => 'Mamar',
                'hasil_pemeriksaan' => 'Suhu tubuh diukur (37.8°C), diberi obat penurun panas dan diminta istirahat. Orang tua dihubungi.',
                'tanggal' => '2025-08-11',
                'created_at' => '2025-08-11 00:00:00',
                'updated_at' => '2025-08-11 00:00:00',
            ],
            [
                'nama_siswa' => 'Fauzan Adriansyah',
                'student_id' => 127,
                'kelas' => 'X D',
                'keluhan' => 'Pusing dan sakit kepala',
                'orang_tua' => 'Dewi',
                'alamat' => 'Telaga Silaba',
                'hasil_pemeriksaan' => 'Diberi obat paracetamol dan diizinkan istirahat di UKS selama 1 jam pelajaran.',
                'tanggal' => '2025-08-04',
                'created_at' => '2025-08-04 00:00:00',
                'updated_at' => '2025-08-04 00:00:00',
            ],
            [
                'nama_siswa' => 'Linda Wati',
                'student_id' => 81,
                'kelas' => 'X C',
                'keluhan' => 'Merasa lemas dan tidak enak badan',
                'orang_tua' => 'Abdul',
                'alamat' => 'Telaga Silaba',
                'hasil_pemeriksaan' => 'Diizinkan pulang setelah orang tua menjemput.',
                'tanggal' => '2025-08-19',
                'created_at' => '2025-08-19 00:00:00',
                'updated_at' => '2025-08-19 00:00:00',
            ],
        ]);
    }
}
