<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KonselingAgustusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('counseling_guidances')->insert([
            [
                'student_id' => 37,
                'nama_siswa' => 'Daffa Al-Hafidz',
                'kelas' => 'X A',
                'tanggal' => '2025-08-05',
                'uraian_masalah' => 'Siswa terlibat konflik dengan teman sekelas.',
                'pemecahan_masalah' => 'Melakukan mediasi antara siswa yang berkonflik, mengajarkan cara berkomunikasi yang baik, dan membuat kesepakatan damai.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 55,
                'nama_siswa' => 'Maya Sari',
                'kelas' => 'X B',
                'tanggal' => '2025-08-05',
                'uraian_masalah' => 'Siswa merasa pilihan karirnya tidak direstui oleh orang tua.',
                'pemecahan_masalah' => 'Mengadakan pertemuan tiga pihak (siswa, orang tua, guru BK) untuk mendiskusikan aspirasi siswa dan pandangan orang tua secara terbuka.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 78,
                'nama_siswa' => 'Agung Setiawan',
                'kelas' => 'X C',
                'tanggal' => '2025-08-12',
                'uraian_masalah' => 'Siswa kesulitan beradaptasi dengan lingkungan pertemanan di kelas.',
                'pemecahan_masalah' => 'Mengajak siswa untuk bergabung dalam kegiatan kelompok, mengenalkannya pada beberapa teman, dan memberikan dukungan moral.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 54,
                'nama_siswa' => 'Eko Prasetyo',
                'kelas' => 'X B',
                'tanggal' => '2025-08-29',
                'uraian_masalah' => 'Siswa mengalami kesulitan fokus saat belajar di kelas dan sering mengantuk.',
                'pemecahan_masalah' => 'Guru BK memberikan strategi manajemen waktu, menyarankan untuk cukup istirahat, dan teknik fokus seperti pomodoro.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 80,
                'nama_siswa' => 'Taufik Hidayat',
                'kelas' => 'X C',
                'tanggal' => '2025-08-29',
                'uraian_masalah' => 'Siswa mengalami kesulitan fokus saat belajar di kelas dan sering mengantuk.',
                'pemecahan_masalah' => 'Guru BK memberikan strategi manajemen waktu, menyarankan untuk cukup istirahat, dan teknik fokus seperti pomodoro.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 82,
                'nama_siswa' => 'Jamaludin',
                'kelas' => 'X C',
                'tanggal' => '2025-08-27',
                'uraian_masalah' => 'Nilai siswa menurun di beberapa mata pelajaran.',
                'pemecahan_masalah' => 'Mengadakan sesi konseling untuk mencari akar masalah, menyarankan untuk mengikuti kelompok belajar, dan berkomunikasi dengan guru mata pelajaran terkait.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 39,
                'nama_siswa' => 'Iqbal Ramadhan',
                'kelas' => 'X A',
                'tanggal' => '2025-08-13',
                'uraian_masalah' => 'Siswa memiliki masalah keluarga yang mengganggu konsentrasi belajarnya.',
                'pemecahan_masalah' => 'Memberikan ruang aman untuk bercerita, menawarkan mediasi jika memungkinkan, dan memberikan pengertian kepada wali kelas.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 52,
                'nama_siswa' => 'Gilang Septian',
                'kelas' => 'X B',
                'tanggal' => '2025-08-28',
                'uraian_masalah' => 'Siswa bingung dalam menentukan pilihan jurusan untuk melanjutkan ke perguruan tinggi.',
                'pemecahan_masalah' => 'Memberikan tes minat bakat, menyajikan informasi mengenai berbagai jurusan dan prospek kerjanya, serta melakukan diskusi tentang cita-cita siswa.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 128,
                'nama_siswa' => 'Dewi',
                'kelas' => 'X D',
                'tanggal' => '2025-08-04',
                'uraian_masalah' => 'Siswa merasa pilihan karirnya tidak direstui oleh orang tua.',
                'pemecahan_masalah' => 'Mengadakan pertemuan tiga pihak (siswa, orang tua, guru BK) untuk mendiskusikan aspirasi siswa dan pandangan orang tua secara terbuka.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 28,
                'nama_siswa' => 'Rizki Maulana Ibrahim',
                'kelas' => 'X A',
                'tanggal' => '2025-08-29',
                'uraian_masalah' => 'Nilai siswa menurun di beberapa mata pelajaran.',
                'pemecahan_masalah' => 'Mengadakan sesi konseling untuk mencari akar masalah, menyarankan untuk mengikuti kelompok belajar, dan berkomunikasi dengan guru mata pelajaran terkait.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 135,
                'nama_siswa' => 'Iqbal',
                'kelas' => 'X D',
                'tanggal' => '2025-08-25',
                'uraian_masalah' => 'Siswa mengalami kesulitan fokus saat belajar di kelas dan sering mengantuk.',
                'pemecahan_masalah' => 'Guru BK memberikan strategi manajemen waktu, menyarankan untuk cukup istirahat, dan teknik fokus seperti pomodoro.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 68,
                'nama_siswa' => 'Rangga Dwi Saputra',
                'kelas' => 'X C',
                'tanggal' => '2025-08-29',
                'uraian_masalah' => 'Siswa merasa pilihan karirnya tidak direstui oleh orang tua.',
                'pemecahan_masalah' => 'Mengadakan pertemuan tiga pihak (siswa, orang tua, guru BK) untuk mendiskusikan aspirasi siswa dan pandangan orang tua secara terbuka.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 138,
                'nama_siswa' => 'Zainab Aliyah',
                'kelas' => 'X D',
                'tanggal' => '2025-08-20',
                'uraian_masalah' => 'Siswa merasa pilihan karirnya tidak direstui oleh orang tua.',
                'pemecahan_masalah' => 'Mengadakan pertemuan tiga pihak (siswa, orang tua, guru BK) untuk mendiskusikan aspirasi siswa dan pandangan orang tua secara terbuka.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 50,
                'nama_siswa' => 'Muhammad Zidan Ramadhan',
                'kelas' => 'X B',
                'tanggal' => '2025-08-18',
                'uraian_masalah' => 'Siswa kesulitan beradaptasi dengan lingkungan pertemanan di kelas.',
                'pemecahan_masalah' => 'Mengajak siswa untuk bergabung dalam kegiatan kelompok, mengenalkannya pada beberapa teman, dan memberikan dukungan moral.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 81,
                'nama_siswa' => 'Linda Wati',
                'kelas' => 'X C',
                'tanggal' => '2025-08-04',
                'uraian_masalah' => 'Nilai siswa menurun di beberapa mata pelajaran.',
                'pemecahan_masalah' => 'Mengadakan sesi konseling untuk mencari akar masalah, menyarankan untuk mengikuti kelompok belajar, dan berkomunikasi dengan guru mata pelajaran terkait.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 41,
                'nama_siswa' => 'Siti Khadijah',
                'kelas' => 'X A',
                'tanggal' => '2025-08-19',
                'uraian_masalah' => 'Siswa bingung dalam menentukan pilihan jurusan untuk melanjutkan ke perguruan tinggi.',
                'pemecahan_masalah' => 'Memberikan tes minat bakat, menyajikan informasi mengenai berbagai jurusan dan prospek kerjanya, serta melakukan diskusi tentang cita-cita siswa.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 123,
                'nama_siswa' => 'Muhammad Alif Pratama',
                'kelas' => 'X D',
                'tanggal' => '2025-08-19',
                'uraian_masalah' => 'Siswa merasa pilihan karirnya tidak direstui oleh orang tua.',
                'pemecahan_masalah' => 'Mengadakan pertemuan tiga pihak (siswa, orang tua, guru BK) untuk mendiskusikan aspirasi siswa dan pandangan orang tua secara terbuka.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 27,
                'nama_siswa' => 'Ahmad Fauzan Al-Ghifari',
                'kelas' => 'X A',
                'tanggal' => '2025-08-27',
                'uraian_masalah' => 'Siswa terlibat konflik dengan teman sekelas.',
                'pemecahan_masalah' => 'Melakukan mediasi antara siswa yang berkonflik, mengajarkan cara berkomunikasi yang baik, dan membuat kesepakatan damai.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 60,
                'nama_siswa' => 'Bayu Anggara',
                'kelas' => 'X B',
                'tanggal' => '2025-08-13',
                'uraian_masalah' => 'Siswa terlihat murung, kurang percaya diri, dan menarik diri dari pergaulan.',
                'pemecahan_masalah' => 'Melakukan pendekatan personal untuk membangun kepercayaan, memberikan motivasi dan afirmasi positif, serta mengajak siswa mengikuti kegiatan ekstrakurikuler yang diminati.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 33,
                'nama_siswa' => 'Yusuf Ali Alatas',
                'kelas' => 'X A',
                'tanggal' => '2025-08-18',
                'uraian_masalah' => 'Siswa mengalami kesulitan fokus saat belajar di kelas dan sering mengantuk.',
                'pemecahan_masalah' => 'Guru BK memberikan strategi manajemen waktu, menyarankan untuk cukup istirahat, dan teknik fokus seperti pomodoro.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 66,
                'nama_siswa' => 'Fahmi Aziz',
                'kelas' => 'X C',
                'tanggal' => '2025-08-29',
                'uraian_masalah' => 'Siswa terlihat murung, kurang percaya diri, dan menarik diri dari pergaulan.',
                'pemecahan_masalah' => 'Melakukan pendekatan personal untuk membangun kepercayaan, memberikan motivasi dan afirmasi positif, serta mengajak siswa mengikuti kegiatan ekstrakurikuler yang diminati.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 74,
                'nama_siswa' => 'Guntur Wibowo',
                'kelas' => 'X C',
                'tanggal' => '2025-08-21',
                'uraian_masalah' => 'Siswa kesulitan beradaptasi dengan lingkungan pertemanan di kelas.',
                'pemecahan_masalah' => 'Mengajak siswa untuk bergabung dalam kegiatan kelompok, mengenalkannya pada beberapa teman, dan memberikan dukungan moral.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 78,
                'nama_siswa' => 'Agung Setiawan',
                'kelas' => 'X C',
                'tanggal' => '2025-08-08',
                'uraian_masalah' => 'Siswa memiliki masalah keluarga yang mengganggu konsentrasi belajarnya.',
                'pemecahan_masalah' => 'Memberikan ruang aman untuk bercerita, menawarkan mediasi jika memungkinkan, dan memberikan pengertian kepada wali kelas.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 138,
                'nama_siswa' => 'Zainab Aliyah',
                'kelas' => 'X D',
                'tanggal' => '2025-08-14',
                'uraian_masalah' => 'Siswa mengalami kesulitan fokus saat belajar di kelas dan sering mengantuk.',
                'pemecahan_masalah' => 'Guru BK memberikan strategi manajemen waktu, menyarankan untuk cukup istirahat, dan teknik fokus seperti pomodoro.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 50,
                'nama_siswa' => 'Muhammad Zidan Ramadhan',
                'kelas' => 'X B',
                'tanggal' => '2025-08-07',
                'uraian_masalah' => 'Siswa merasa pilihan karirnya tidak direstui oleh orang tua.',
                'pemecahan_masalah' => 'Mengadakan pertemuan tiga pihak (siswa, orang tua, guru BK) untuk mendiskusikan aspirasi siswa dan pandangan orang tua secara terbuka.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 79,
                'nama_siswa' => 'Vina Panduwinata',
                'kelas' => 'X C',
                'tanggal' => '2025-08-08',
                'uraian_masalah' => 'Siswa memiliki masalah keluarga yang mengganggu konsentrasi belajarnya.',
                'pemecahan_masalah' => 'Memberikan ruang aman untuk bercerita, menawarkan mediasi jika memungkinkan, dan memberikan pengertian kepada wali kelas.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 61,
                'nama_siswa' => 'Lia Agustina',
                'kelas' => 'X B',
                'tanggal' => '2025-08-22',
                'uraian_masalah' => 'Siswa kesulitan beradaptasi dengan lingkungan pertemanan di kelas.',
                'pemecahan_masalah' => 'Mengajak siswa untuk bergabung dalam kegiatan kelompok, mengenalkannya pada beberapa teman, dan memberikan dukungan moral.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 70,
                'nama_siswa' => 'Irfan Hakim',
                'kelas' => 'X C',
                'tanggal' => '2025-08-15',
                'uraian_masalah' => 'Siswa kesulitan beradaptasi dengan lingkungan pertemanan di kelas.',
                'pemecahan_masalah' => 'Mengajak siswa untuk bergabung dalam kegiatan kelompok, mengenalkannya pada beberapa teman, dan memberikan dukungan moral.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 52,
                'nama_siswa' => 'Gilang Septian',
                'kelas' => 'X B',
                'tanggal' => '2025-08-22',
                'uraian_masalah' => 'Siswa memiliki masalah keluarga yang mengganggu konsentrasi belajarnya.',
                'pemecahan_masalah' => 'Memberikan ruang aman untuk bercerita, menawarkan mediasi jika memungkinkan, dan memberikan pengertian kepada wali kelas.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 59,
                'nama_siswa' => 'Zahra Cantika',
                'kelas' => 'X B',
                'tanggal' => '2025-08-11',
                'uraian_masalah' => 'Nilai siswa menurun di beberapa mata pelajaran.',
                'pemecahan_masalah' => 'Mengadakan sesi konseling untuk mencari akar masalah, menyarankan untuk mengikuti kelompok belajar, dan berkomunikasi dengan guru mata pelajaran terkait.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
        ]);
    }
}
