<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class KonselingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('counseling_guidances')->insert([
            [
                'student_id' => 80,
                'nama_siswa' => 'Taufik Hidayat',
                'kelas' => 'X C',
                'tanggal' => '2025-07-16',
                'uraian_masalah' => 'Siswa kesulitan beradaptasi dengan lingkungan pertemanan di kelas.',
                'pemecahan_masalah' => 'Mengajak siswa untuk bergabung dalam kegiatan kelompok, mengenalkannya pada beberapa teman, dan memberikan dukungan moral.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 139,
                'nama_siswa' => 'Aditya',
                'kelas' => 'X D',
                'tanggal' => '2025-07-22',
                'uraian_masalah' => 'Siswa mengalami kesulitan fokus saat belajar di kelas dan sering mengantuk.',
                'pemecahan_masalah' => 'Guru BK memberikan strategi manajemen waktu, menyarankan untuk cukup istirahat, dan teknik fokus seperti pomodoro.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 137,
                'nama_siswa' => 'Dimas Setiawan',
                'kelas' => 'X D',
                'tanggal' => '2025-07-22',
                'uraian_masalah' => 'Siswa terlihat murung, kurang percaya diri, dan menarik diri dari pergaulan.',
                'pemecahan_masalah' => 'Melakukan pendekatan personal untuk membangun kepercayaan, memberikan motivasi dan afirmasi positif, serta mengajak siswa mengikuti kegiatan ekstrakurikuler yang diminati.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 49,
                'nama_siswa' => 'Dewi Lestari',
                'kelas' => 'X B',
                'tanggal' => '2025-07-18',
                'uraian_masalah' => 'Nilai siswa menurun di beberapa mata pelajaran.',
                'pemecahan_masalah' => 'Mengadakan sesi konseling untuk mencari akar masalah, menyarankan untuk mengikuti kelompok belajar, dan berkomunikasi dengan guru mata pelajaran terkait.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 72,
                'nama_siswa' => 'Reza Ardiyansah',
                'kelas' => 'X C',
                'tanggal' => '2025-07-29',
                'uraian_masalah' => 'Siswa mengalami kesulitan fokus saat belajar di kelas dan sering mengantuk.',
                'pemecahan_masalah' => 'Guru BK memberikan strategi manajemen waktu, menyarankan untuk cukup istirahat, dan teknik fokus seperti pomodoro.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 38,
                'nama_siswa' => 'Khairul Azzam',
                'kelas' => 'X A',
                'tanggal' => '2025-07-22',
                'uraian_masalah' => 'Siswa memiliki masalah keluarga yang mengganggu konsentrasi belajarnya.',
                'pemecahan_masalah' => 'Memberikan ruang aman untuk bercerita, menawarkan mediasi jika memungkinkan, dan memberikan pengertian kepada wali kelas.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 32,
                'nama_siswa' => 'Annisa Fitriani',
                'kelas' => 'X A',
                'tanggal' => '2025-07-15',
                'uraian_masalah' => 'Nilai siswa menurun di beberapa mata pelajaran.',
                'pemecahan_masalah' => 'Mengadakan sesi konseling untuk mencari akar masalah, menyarankan untuk mengikuti kelompok belajar, dan berkomunikasi dengan guru mata pelajaran terkait.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => 1,
            ],
            [
                'student_id' => 32,
                'nama_siswa' => 'Annisa Fitriani',
                'kelas' => 'X A',
                'tanggal' => '2025-07-17',
                'uraian_masalah' => 'Siswa merasa pilihan karirnya tidak direstui oleh orang tua.',
                'pemecahan_masalah' => 'Mengadakan pertemuan tiga pihak (siswa, orang tua, guru BK) untuk mendiskusikan aspirasi siswa dan pandangan orang tua secara terbuka.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 141,
                'nama_siswa' => 'Reza',
                'kelas' => 'X D',
                'tanggal' => '2025-07-28',
                'uraian_masalah' => 'Siswa terlibat konflik dengan teman sekelas.',
                'pemecahan_masalah' => 'Melakukan mediasi antara siswa yang berkonflik, mengajarkan cara berkomunikasi yang baik, dan membuat kesepakatan damai.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 46,
                'nama_siswa' => 'Rizky Akbar Pratama',
                'kelas' => 'X B',
                'tanggal' => '2025-07-24',
                'uraian_masalah' => 'Siswa terlihat murung, kurang percaya diri, dan menarik diri dari pergaulan.',
                'pemecahan_masalah' => 'Melakukan pendekatan personal untuk membangun kepercayaan, memberikan motivasi dan afirmasi positif, serta mengajak siswa mengikuti kegiatan ekstrakurikuler yang diminati.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 130,
                'nama_siswa' => 'Indah Permatasari',
                'kelas' => 'X D',
                'tanggal' => '2025-07-18',
                'uraian_masalah' => 'Siswa terlibat konflik dengan teman sekelas.',
                'pemecahan_masalah' => 'Melakukan mediasi antara siswa yang berkonflik, mengajarkan cara berkomunikasi yang baik, dan membuat kesepakatan damai.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 136,
                'nama_siswa' => 'Aminah Hasanah',
                'kelas' => 'X D',
                'tanggal' => '2025-07-22',
                'uraian_masalah' => 'Siswa terlihat murung, kurang percaya diri, dan menarik diri dari pergaulan.',
                'pemecahan_masalah' => 'Melakukan pendekatan personal untuk membangun kepercayaan, memberikan motivasi dan afirmasi positif, serta mengajak siswa mengikuti kegiatan ekstrakurikuler yang diminati.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 66,
                'nama_siswa' => 'Fahmi Aziz',
                'kelas' => 'X C',
                'tanggal' => '2025-07-29',
                'uraian_masalah' => 'Siswa merasa pilihan karirnya tidak direstui oleh orang tua.',
                'pemecahan_masalah' => 'Mengadakan pertemuan tiga pihak (siswa, orang tua, guru BK) untuk mendiskusikan aspirasi siswa dan pandangan orang tua secara terbuka.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 70,
                'nama_siswa' => 'Irfan Hakim',
                'kelas' => 'X C',
                'tanggal' => '2025-07-18',
                'uraian_masalah' => 'Siswa bingung dalam menentukan pilihan jurusan untuk melanjutkan ke perguruan tinggi.',
                'pemecahan_masalah' => 'Memberikan tes minat bakat, menyajikan informasi mengenai berbagai jurusan dan prospek kerjanya, serta melakukan diskusi tentang cita-cita siswa.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 140,
                'nama_siswa' => 'Yasmin Salsabila',
                'kelas' => 'X D',
                'tanggal' => '2025-07-15',
                'uraian_masalah' => 'Siswa merasa pilihan karirnya tidak direstui oleh orang tua.',
                'pemecahan_masalah' => 'Mengadakan pertemuan tiga pihak (siswa, orang tua, guru BK) untuk mendiskusikan aspirasi siswa dan pandangan orang tua secara terbuka.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 27,
                'nama_siswa' => 'Ahmad Fauzan Al-Ghifari',
                'kelas' => 'X A',
                'tanggal' => '2025-07-15',
                'uraian_masalah' => 'Siswa terlihat murung, kurang percaya diri, dan menarik diri dari pergaulan.',
                'pemecahan_masalah' => 'Melakukan pendekatan personal untuk membangun kepercayaan, memberikan motivasi dan afirmasi positif, serta mengajak siswa mengikuti kegiatan ekstrakurikuler yang diminati.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 55,
                'nama_siswa' => 'Maya Sari',
                'kelas' => 'X B',
                'tanggal' => '2025-07-21',
                'uraian_masalah' => 'Siswa memiliki masalah keluarga yang mengganggu konsentrasi belajarnya.',
                'pemecahan_masalah' => 'Memberikan ruang aman untuk bercerita, menawarkan mediasi jika memungkinkan, dan memberikan pengertian kepada wali kelas.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 126,
                'nama_siswa' => 'Nurul',
                'kelas' => 'X D',
                'tanggal' => '2025-07-16',
                'uraian_masalah' => 'Siswa merasa pilihan karirnya tidak direstui oleh orang tua.',
                'pemecahan_masalah' => 'Mengadakan pertemuan tiga pihak (siswa, orang tua, guru BK) untuk mendiskusikan aspirasi siswa dan pandangan orang tua secara terbuka.',
                'is_pribadi' => null,
                'is_sosial' => null,
                'is_karir' => 1,
                'is_belajar' => null,
            ],
            [
                'student_id' => 40,
                'nama_siswa' => 'Aditya Nugraha',
                'kelas' => 'X A',
                'tanggal' => '2025-07-24',
                'uraian_masalah' => 'Siswa terlihat murung, kurang percaya diri, dan menarik diri dari pergaulan.',
                'pemecahan_masalah' => 'Melakukan pendekatan personal untuk membangun kepercayaan, memberikan motivasi dan afirmasi positif, serta mengajak siswa mengikuti kegiatan ekstrakurikuler yang diminati.',
                'is_pribadi' => 1,
                'is_sosial' => null,
                'is_karir' => null,
                'is_belajar' => null,
            ],
            [
                'student_id' => 46,
                'nama_siswa' => 'Rizky Akbar Pratama',
                'kelas' => 'X B',
                'tanggal' => '2025-07-25',
                'uraian_masalah' => 'Siswa terlibat konflik dengan teman sekelas.',
                'pemecahan_masalah' => 'Melakukan mediasi antara siswa yang berkonflik, mengajarkan cara berkomunikasi yang baik, dan membuat kesepakatan damai.',
                'is_pribadi' => null,
                'is_sosial' => 1,
                'is_karir' => null,
                'is_belajar' => null,
            ],
        ]);
    }
}
