<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LateArrivalSeederPart4 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('late_arrivals')->insert([
            [
                'student_id' => 53,
                'nama_siswa' => 'Nadia Aulia',
                'guru_piket' => 'Siti Nur Hamidah, S.Si.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-04',
                'waktu_datang' => '08:49:01',
            ],
            [
                'student_id' => 40,
                'nama_siswa' => 'Aditya Nugraha',
                'guru_piket' => 'Siti Nur Hamidah, S.Si.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-04',
                'waktu_datang' => '08:44:47',
            ],
            [
                'student_id' => 77,
                'nama_siswa' => 'Rina Amelia',
                'guru_piket' => 'Siti Ramadhah, S.Pd.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-04',
                'waktu_datang' => '08:54:04',
            ],
            [
                'student_id' => 57,
                'nama_siswa' => 'Putri Wulandari',
                'guru_piket' => 'Hj. Lisa Indianawati, S.Pd.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-05',
                'waktu_datang' => '08:57:52',
            ],
            [
                'student_id' => 53,
                'nama_siswa' => 'Nadia Aulia',
                'guru_piket' => 'Mahdian S.Pd.I.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-05',
                'waktu_datang' => '08:56:52',
            ],
            [
                'student_id' => 128,
                'nama_siswa' => 'Dewi',
                'guru_piket' => 'H. Ahd. Pauzi. S.Pd.I.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-05',
                'waktu_datang' => '08:48:48',
            ],
            [
                'student_id' => 84,
                'nama_siswa' => 'Kamal Pasya',
                'guru_piket' => 'Syarif Hamidillah, S.Pd.I.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-06',
                'waktu_datang' => '08:52:56',
            ],
            [
                'student_id' => 39,
                'nama_siswa' => 'Iqbal Ramadhan',
                'guru_piket' => 'Noor Hidayati, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-06',
                'waktu_datang' => '08:51:30',
            ],
            [
                'student_id' => 56,
                'nama_siswa' => 'Rian Hidayatullah',
                'guru_piket' => 'Hj. Rabiatul Adawiyah, S.Ag.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-06',
                'waktu_datang' => '08:47:08',
            ],
            [
                'student_id' => 37,
                'nama_siswa' => 'Daffa Al-Hafidz',
                'guru_piket' => 'Norhadiah, S.Ag.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-06',
                'waktu_datang' => '08:56:38',
            ],
            [
                'student_id' => 56,
                'nama_siswa' => 'Rian Hidayatullah',
                'guru_piket' => 'Pahmi, S.Ag.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-07',
                'waktu_datang' => '08:54:48',
            ],
            [
                'student_id' => 50,
                'nama_siswa' => 'Muhammad Zidan Ramadhan',
                'guru_piket' => 'Siti Nur Hamidah, S.Si.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-07',
                'waktu_datang' => '08:50:04',
            ],
            [
                'student_id' => 65,
                'nama_siswa' => 'Wildan Al-Farisi',
                'guru_piket' => 'Noor Hidayati, S.Pd.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-07',
                'waktu_datang' => '08:54:06',
            ],
            [
                'student_id' => 55,
                'nama_siswa' => 'Maya Sari',
                'guru_piket' => 'Hairullah, S.Hum.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-07',
                'waktu_datang' => '08:44:29',
            ],
            [
                'student_id' => 141,
                'nama_siswa' => 'Reza',
                'guru_piket' => 'H. Sauqil Ajmi, S.Pd.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-08',
                'waktu_datang' => '08:46:53',
            ],
            [
                'student_id' => 26,
                'nama_siswa' => 'Muhammad Farhan Abdullah',
                'guru_piket' => 'Noor Hidayati, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-08',
                'waktu_datang' => '08:46:25',
            ],
            [
                'student_id' => 62,
                'nama_siswa' => 'Dimas Saputra',
                'guru_piket' => 'Rahimah S.Ag.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-08',
                'waktu_datang' => '08:52:01',
            ],
            [
                'student_id' => 55,
                'nama_siswa' => 'Maya Sari',
                'guru_piket' => 'Rahmadhani Fadli, S.Pd.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-08',
                'waktu_datang' => '08:40:28',
            ],
            [
                'student_id' => 43,
                'nama_siswa' => 'Hasan Basri',
                'guru_piket' => 'Hj. Norhidayati,S.Ag.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-08',
                'waktu_datang' => '08:52:37',
            ],
            [
                'student_id' => 46,
                'nama_siswa' => 'Rizky Akbar Pratama',
                'guru_piket' => 'Hj. Rabiatul Adawiyah, S.Ag.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-11',
                'waktu_datang' => '08:41:45',
            ],
            [
                'student_id' => 48,
                'nama_siswa' => 'Fajar Maulana Siddiq',
                'guru_piket' => 'Ramdan Syahrin, S.Ag.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-11',
                'waktu_datang' => '08:40:49',
            ],
            [
                'student_id' => 47,
                'nama_siswa' => 'Annisa Rahmawati',
                'guru_piket' => 'Hj. Lisa Indianawati, S.Pd.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-11',
                'waktu_datang' => '08:40:11',
            ],
            [
                'student_id' => 62,
                'nama_siswa' => 'Dimas Saputra',
                'guru_piket' => 'Mahdian S.Pd.I.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-11',
                'waktu_datang' => '08:43:58',
            ],
            [
                'student_id' => 48,
                'nama_siswa' => 'Fajar Maulana Siddiq',
                'guru_piket' => 'Muhammad Rezky Maulana, S.Pd.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-12',
                'waktu_datang' => '08:48:31',
            ],
            [
                'student_id' => 30,
                'nama_siswa' => 'Nurul Hidayah',
                'guru_piket' => 'Syaifullah, S.Ag., M.Ag.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-12',
                'waktu_datang' => '08:51:12',
            ],
            [
                'student_id' => 37,
                'nama_siswa' => 'Daffa Al-Hafidz',
                'guru_piket' => 'Hj. Lisa Indianawati, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-12',
                'waktu_datang' => '08:55:00',
            ],
            [
                'student_id' => 39,
                'nama_siswa' => 'Iqbal Ramadhan',
                'guru_piket' => 'Sri Yanti, S.Pd.I.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-12',
                'waktu_datang' => '08:59:21',
            ],
            [
                'student_id' => 45,
                'nama_siswa' => 'Yasmin Nadhira',
                'guru_piket' => 'Muhammad Rezky Maulana, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-12',
                'waktu_datang' => '08:52:00',
            ],
            [
                'student_id' => 79,
                'nama_siswa' => 'Vina Panduwinata',
                'guru_piket' => 'Hj. Mahmudah, S.Pd.I.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-13',
                'waktu_datang' => '08:53:53',
            ],
            [
                'student_id' => 72,
                'nama_siswa' => 'Reza Ardiyansah',
                'guru_piket' => 'H. Ahd. Pauzi. S.Pd.I.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-13',
                'waktu_datang' => '08:56:13',
            ],
            [
                'student_id' => 132,
                'nama_siswa' => 'Fatimah Azzahra',
                'guru_piket' => 'Ridha Mukhlisah, S.Pd.I.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-13',
                'waktu_datang' => '08:47:36',
            ],
            [
                'student_id' => 35,
                'nama_siswa' => 'Abdul Rahman Hakim',
                'guru_piket' => 'H. Sauqil Ajmi, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-13',
                'waktu_datang' => '08:48:14',
            ],
            [
                'student_id' => 37,
                'nama_siswa' => 'Daffa Al-Hafidz',
                'guru_piket' => 'Paturrahman,S.Ag.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-13',
                'waktu_datang' => '08:55:09',
            ],
            [
                'student_id' => 71,
                'nama_siswa' => 'Sari Mutiara',
                'guru_piket' => 'Ramdan Syahrin, S.Ag.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-14',
                'waktu_datang' => '08:42:47',
            ],
            [
                'student_id' => 135,
                'nama_siswa' => 'Iqbal',
                'guru_piket' => 'Ridha Mukhlisah, S.Pd.I.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-14',
                'waktu_datang' => '08:54:48',
            ],
            [
                'student_id' => 41,
                'nama_siswa' => 'Siti Khadijah',
                'guru_piket' => 'Mahdian S.Pd.I.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-14',
                'waktu_datang' => '08:40:50',
            ],
            [
                'student_id' => 129,
                'nama_siswa' => 'Arif Rahman Hakim',
                'guru_piket' => 'Hj. Mahmudah, S.Pd.I.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-15',
                'waktu_datang' => '08:48:54',
            ],
            [
                'student_id' => 61,
                'nama_siswa' => 'Lia Agustina',
                'guru_piket' => 'Ahmad Muttaqin, S.Pd.I.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-15',
                'waktu_datang' => '08:55:09',
            ],
            [
                'student_id' => 136,
                'nama_siswa' => 'Aminah Hasanah',
                'guru_piket' => 'Mahdian S.Pd.I.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-15',
                'waktu_datang' => '08:54:18',
            ],
            [
                'student_id' => 75,
                'nama_siswa' => 'Wulan Dari',
                'guru_piket' => 'Syarif Hamidillah, S.Pd.I.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-18',
                'waktu_datang' => '08:43:59',
            ],
            [
                'student_id' => 37,
                'nama_siswa' => 'Daffa Al-Hafidz',
                'guru_piket' => 'Norhadiah, S.Ag.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-18',
                'waktu_datang' => '08:47:14',
            ],
            [
                'student_id' => 127,
                'nama_siswa' => 'Fauzan Adriansyah',
                'guru_piket' => 'Zainal Anhar, S.Ag.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-18',
                'waktu_datang' => '08:45:55',
            ],
            [
                'student_id' => 139,
                'nama_siswa' => 'Aditya',
                'guru_piket' => 'Syaifullah, S.Ag., M.Ag.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-18',
                'waktu_datang' => '08:42:25',
            ],
            [
                'student_id' => 69,
                'nama_siswa' => 'Aulia Putri Salsabila',
                'guru_piket' => 'Farida Rahmi, S.Pd.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-18',
                'waktu_datang' => '08:49:40',
            ],
            [
                'student_id' => 138,
                'nama_siswa' => 'Zainab Aliyah',
                'guru_piket' => 'Anita, S.Pd.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-19',
                'waktu_datang' => '08:53:04',
            ],
            [
                'student_id' => 64,
                'nama_siswa' => 'Citra Kirana',
                'guru_piket' => 'Tutilawati, S.Pd.I.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-19',
                'waktu_datang' => '08:46:02',
            ],
            [
                'student_id' => 28,
                'nama_siswa' => 'Rizki Maulana Ibrahim',
                'guru_piket' => 'H. Sauqil Ajmi, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-19',
                'waktu_datang' => '08:48:00',
            ],
            [
                'student_id' => 124,
                'nama_siswa' => 'Siti Aisyah',
                'guru_piket' => 'Tutilawati, S.Pd.I.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-19',
                'waktu_datang' => '08:44:46',
            ],
            [
                'student_id' => 30,
                'nama_siswa' => 'Nurul Hidayah',
                'guru_piket' => 'Pahmi, S.Ag.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-19',
                'waktu_datang' => '08:44:26',
            ],
            [
                'student_id' => 43,
                'nama_siswa' => 'Hasan Basri',
                'guru_piket' => 'Maulidah Hasanah, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-20',
                'waktu_datang' => '08:59:32',
            ],
            [
                'student_id' => 74,
                'nama_siswa' => 'Guntur Wibowo',
                'guru_piket' => 'Muhammad Rezky Maulana, S.Pd.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-20',
                'waktu_datang' => '08:54:12',
            ],
            [
                'student_id' => 32,
                'nama_siswa' => 'Annisa Fitriani',
                'guru_piket' => 'Tutilawati, S.Pd.I.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-20',
                'waktu_datang' => '08:55:42',
            ],
            [
                'student_id' => 49,
                'nama_siswa' => 'Dewi Lestari',
                'guru_piket' => 'Hj. Lisa Indianawati, S.Pd.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-20',
                'waktu_datang' => '08:59:49',
            ],
            [
                'student_id' => 54,
                'nama_siswa' => 'Eko Prasetyo',
                'guru_piket' => 'Tutilawati, S.Pd.I.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-21',
                'waktu_datang' => '08:48:26',
            ],
            [
                'student_id' => 59,
                'nama_siswa' => 'Zahra Cantika',
                'guru_piket' => 'Hairullah, S.Hum.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-21',
                'waktu_datang' => '08:51:26',
            ],
            [
                'student_id' => 58,
                'nama_siswa' => 'Arif Budiman',
                'guru_piket' => 'Hj. Lisa Indianawati, S.Pd.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-21',
                'waktu_datang' => '08:40:10',
            ],
            [
                'student_id' => 42,
                'nama_siswa' => 'Putri Amelia',
                'guru_piket' => 'Hj. Lisa Indianawati, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-22',
                'waktu_datang' => '08:42:18',
            ],
            [
                'student_id' => 62,
                'nama_siswa' => 'Dimas Saputra',
                'guru_piket' => 'Tutilawati, S.Pd.I.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-22',
                'waktu_datang' => '08:49:39',
            ],
            [
                'student_id' => 33,
                'nama_siswa' => 'Yusuf Ali Alatas',
                'guru_piket' => 'Nazaruddin, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-22',
                'waktu_datang' => '08:47:41',
            ],
            [
                'student_id' => 46,
                'nama_siswa' => 'Rizky Akbar Pratama',
                'guru_piket' => 'Hairullah, S.Hum.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-22',
                'waktu_datang' => '08:41:07',
            ],
            [
                'student_id' => 70,
                'nama_siswa' => 'Irfan Hakim',
                'guru_piket' => 'Siti Ramadhah, S.Pd.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-25',
                'waktu_datang' => '08:46:16',
            ],
            [
                'student_id' => 126,
                'nama_siswa' => 'Nurul',
                'guru_piket' => 'Pahmi, S.Ag.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-25',
                'waktu_datang' => '08:53:09',
            ],
            [
                'student_id' => 124,
                'nama_siswa' => 'Siti Aisyah',
                'guru_piket' => 'Tutilawati, S.Pd.I.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-25',
                'waktu_datang' => '08:54:37',
            ],
            [
                'student_id' => 77,
                'nama_siswa' => 'Rina Amelia',
                'guru_piket' => 'Ramdan Syahrin, S.Ag.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-25',
                'waktu_datang' => '08:46:07',
            ],
            [
                'student_id' => 84,
                'nama_siswa' => 'Kamal Pasya',
                'guru_piket' => 'Siti Nur Hamidah, S.Si.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-26',
                'waktu_datang' => '08:53:29',
            ],
            [
                'student_id' => 35,
                'nama_siswa' => 'Abdul Rahman Hakim',
                'guru_piket' => 'Rahmadhani Fadli, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-26',
                'waktu_datang' => '08:49:26',
            ],
            [
                'student_id' => 135,
                'nama_siswa' => 'Iqbal',
                'guru_piket' => 'Anita, S.Pd.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-26',
                'waktu_datang' => '08:44:35',
            ],
            [
                'student_id' => 72,
                'nama_siswa' => 'Reza Ardiyansah',
                'guru_piket' => 'Anita, S.Pd.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-27',
                'waktu_datang' => '08:56:37',
            ],
            [
                'student_id' => 123,
                'nama_siswa' => 'Muhammad Alif Pratama',
                'guru_piket' => 'Hj. Lisa Indianawati, S.Pd.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-27',
                'waktu_datang' => '08:43:42',
            ],
            [
                'student_id' => 127,
                'nama_siswa' => 'Fauzan Adriansyah',
                'guru_piket' => 'H. Ahd. Pauzi. S.Pd.I.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-27',
                'waktu_datang' => '08:58:19',
            ],
            [
                'student_id' => 135,
                'nama_siswa' => 'Iqbal',
                'guru_piket' => 'Hj. Norhidayati,S.Ag.',
                'kelas' => 'X D',
                'tanggal' => '2025-08-27',
                'waktu_datang' => '08:59:39',
            ],
            [
                'student_id' => 63,
                'nama_siswa' => 'Aulia Rahman',
                'guru_piket' => 'Muhammad Rezky Maulana, S.Pd.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-28',
                'waktu_datang' => '08:49:52',
            ],
            [
                'student_id' => 74,
                'nama_siswa' => 'Guntur Wibowo',
                'guru_piket' => 'Rahmadhani Fadli, S.Pd.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-28',
                'waktu_datang' => '08:45:59',
            ],
            [
                'student_id' => 80,
                'nama_siswa' => 'Taufik Hidayat',
                'guru_piket' => 'Hj. Mahmudah, S.Pd.I.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-28',
                'waktu_datang' => '08:49:21',
            ],
            [
                'student_id' => 33,
                'nama_siswa' => 'Yusuf Ali Alatas',
                'guru_piket' => 'Rahmadhani Fadli, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-29',
                'waktu_datang' => '08:52:05',
            ],
            [
                'student_id' => 47,
                'nama_siswa' => 'Annisa Rahmawati',
                'guru_piket' => 'Mahdian S.Pd.I.',
                'kelas' => 'X B',
                'tanggal' => '2025-08-29',
                'waktu_datang' => '08:58:18',
            ],
            [
                'student_id' => 71,
                'nama_siswa' => 'Sari Mutiara',
                'guru_piket' => 'Muhammad Rezky Maulana, S.Pd.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-29',
                'waktu_datang' => '08:41:21',
            ],
            [
                'student_id' => 66,
                'nama_siswa' => 'Fahmi Aziz',
                'guru_piket' => 'Mahdian S.Pd.I.',
                'kelas' => 'X C',
                'tanggal' => '2025-08-29',
                'waktu_datang' => '08:41:08',
            ],
            [
                'student_id' => 42,
                'nama_siswa' => 'Putri Amelia',
                'guru_piket' => 'Farida Rahmi, S.Pd.',
                'kelas' => 'X A',
                'tanggal' => '2025-08-29',
                'waktu_datang' => '08:59:56',
            ],
        ]);
    }
}
